{
 "title": "LXD Container Dashboard",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "instance",
    "label": "Instance",
    "query": "label_values(lxc_container_host_cpu_total,instance)"
   },
   {
    "name": "container",
    "label": "Container",
    "query": "label_values(lxc_container_container_status{instance=~\"$instance\"},container_name)"
   }
  ]
 },
 "panels": [
  {
   "title": "Container Status",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "lxc_container_container_status{container_name=~\"$container\",instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "Disk Usage",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 0 },
   "format": "decgbytes",
   "valueName": "avg",
   "targets": [
    {
     "expr": "lxc_container_disk_usage{container_name=~\"$container\",instance=~\"$instance\"} / 1024 / 1024 / 1024"
    }
   ]
  },
  {
   "title": "Instance CPU Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    { "expr": "100", "legendFormat": "Total" },
    {
     "expr": "((rate(lxc_container_cpu_usage{container_name=~\"$container\",instance=~\"$instance\"}[1m]) / 10000000 )  / scalar(lxc_container_host_cpu_total{instance=\"$instance\"}))",
     "legendFormat": "first"
    }
   ]
  },
  {
   "title": "Number of Processes",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 4 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "lxc_container_process_count{container_name=~\"$container\",instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "Swap Usage",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 4 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "lxc_container_container_status{container_name=~\"$container\",instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "Network",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "KBs" }
   ],
   "targets": [
    {
     "expr": "sum(rate(lxc_container_container_network_usage{container_name=~\"$container\",instance=~\"$instance\"}[1m])) by (interface,operation) / 1024"
    }
   ]
  },
  {
   "title": "Memory Utilization",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "decmbytes" }
   ],
   "targets": [
    {
     "expr": "lxc_container_host_mem_total{instance=~\"$instance\"} / 1024 / 1024",
     "legendFormat": "Total"
    },
    {
     "expr": "lxc_container_mem_usage{container_name=~\"$container\",instance=~\"$instance\"} / 1024 / 1024",
     "legendFormat": "first"
    }
   ]
  }
 ]
}